export {ClassComponent1} from './ClassComponent1'
export {ClassComponent2} from './ClassComponent2'
export {ClassComponent3} from './ClassComponent3'
export {default as FuncComponent1} from './FuncComponent1'
export {default as FuncComponent2} from './FuncComponent2'
export {default as FuncComponent3} from './FuncComponent3'
